<div class="col-lg-3 col-md-6">
    <div class="thumbnail">
        <img src="http://placehold.it/800x500" alt="">
        <div class="caption">
            <h3><?php echo $street; ?></h3>
            <p><?php echo $description; ?></p>
            <p><?php echo $price; ?></p>
            <p>
                <a href="#" class="btn btn-primary">Kopen</a>
                <a href="/location/show/locationId=<?php echo $id; ?>/" class="btn">meer info</a>
            </p>
        </div>
    </div>
</div>