<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Web2 webshop webmakelaar">
        <meta name="author" content="Yorick & Patrick">

        <title>Webmakelaar
            <?php
            if (isset($pageTitle)):
                echo sprintf(" :: %s", $pageTitle);
            endif;
            ?>
        </title>

        <link href="/public/css/bootstrap.css" rel="stylesheet">
        <link href="/public/css/custom.css" rel="stylesheet">
    </head>

    <body>

        <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/web2">Home</a>
                </div>


                <?php
                include "navigation.phtml";
                ?>
                </div>
                <!-- /.container -->
        </nav>

        <div class="container">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">Library</a></li>
                <li class="active">Data</li>
            </ol>