<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <?php
        $link = "<li><a href=\"%s\">%s</a></li>";
        foreach ($nav as $navItem):
            /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
            if ($navItem->hasChildren()):
                include "subNavigation.phtml";
            else:
                echo sprintf($link, $navItem->getUri(), $navItem->getName());
            endif;
        endforeach;
        ?>
    </ul>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Multi Level <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Level 1</a></li>
                <li class="dropdown-submenu"> <a tabindex="-1" href="#">More options</a>
                    <ul class="dropdown-menu">
                        <li><a tabindex="-1" href="#">Level 2</a>
                        </li>
                        <li class="dropdown-submenu"> <a href="#">More..</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Level 3</a>
                                </li>
                                <li><a href="#">Level 3</a>
                                </li>
                                <li class="dropdown-submenu"> <a href="#">More..</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li class="dropdown-submenu"> <a href="#">More..</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Level 5</a>
                                                </li>
                                                <li><a href="#">Level 5</a>
                                                </li>
                                            </ul>
                                        </li>

                                    </ul>
                                </li>

                            </ul>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                    </ul>
                </li>
                <li><a href="#">Level 1</a></li>
            </ul>
        </li>
    </ul>
</div>
<!-- /.navbar-collapse -->