<li class="dropdown">
    <?php
    $menuLink = "<a href=\"%s\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">%s <b class=\"caret\"></b></a>";

    echo sprintf($menuLink, $navItem->getUri(), $navItem->getName());
    ?>

    <ul class="dropdown-menu">
        <?php
        $link = "<li><a href=\"%s\">%s</a></li>";
        foreach ($navItem->getChildren() as $childNav):
            echo sprintf($link, $childNav->getUri(), $childNav->getName());
        endforeach;
        ?>
    </ul>
</li>
