<?php

use Aggressiveswallow\Helpers\buttonHelper as Button;

/* @var $location \Aggressiveswallow\Models\Location */

include VIEW_PATH . "partials/header.phtml";
?>
<div class="row">
    <div class="page-header">
        <h1>Winkelwagen <small>Overzicht</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8">
        <?php
        /* @var $cart \Aggressiveswallow\Helpers\Cart */

        if ($cart->hasItems()):
            ?>
            <table class = "table table-hover">
                <thead>
                    <tr>
                        <th>Straat</th>
                        <th>Plaats</th>
                        <th>Postcode</th>
                        <th>Wijk</th>
                        <th colspan="2">Koopprijs</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($cart->getItems() as $product):
                        /* @var $address \Aggressiveswallow\Models\Address */
                        $address = $product->getAddress();

                        $street = $address->getFullStreetName();
                        $zip = $address->getZipcode();
                        $city = $address->getCity();
                        $neighborhood = $address->getNeighborhood();
                        $price = $product->getFormattedPrice();

                        $link = "<td><a href=\"/cart/remove/locationId=%s/\"><span class=\"glyphicon glyphicon-trash\"></span></a></td>";
                        $remLink = sprintf($link, $product->getId());
                        $row = "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td>%s</tr>";
                        printf($row, $street, $city, $zip, $neighborhood, $price, $remLink);
                    endforeach;
                    ?>
                    <tr class="active">
                        <td colspan="3"></td>
                        <td><strong>Totaal prijs: </strong></td>
                        <td colspan="2"><?php echo $cart->getFormattedTotalPrice(); ?></td>
                    </tr>
                </tbody>
            </table>
            <?php
        endif;
        ?>
    </div>
    <div class = "col-xs-6 col-md-4">
        <div class = "panel panel-default">
            <div class = "panel-heading">Kpje</div>
            <div class = "panel-body">
                <p>
                    <strong>Postadres</strong><br/>
                    Iets
                </p>
            </div>
        </div>
    </div>
</div>
<?php
include VIEW_PATH . "partials/footer.phtml";
