<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Webmakelaar :: Inloggen</title>
    <link href="/public/css/bootstrap.css" rel="stylesheet">
    <link href="/public/css/signin.css" rel="stylesheet">
  </head>

  <body>

    <div class="container">

      <form class="form-signin" role="form">
        <h2 class="form-signin-heading">Inloggen</h2>
        <input type="email" class="form-control" placeholder="Gebruikersnaam" required autofocus>
        <input type="password" class="form-control" placeholder="Wachtwoord" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Vergeet me niet
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Inloggen</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>
