<?php

use Aggressiveswallow\Tools\Container;
use Aggressiveswallow\Helpers\Cart;
use \Aggressiveswallow\Helpers\Loggedin;
?>
<div class = "collapse navbar-collapse">
    <ul class = "nav navbar-nav">
        <?php
        $regularLink = "<li><a href=\"%s\">%s</a></li>";
        $nav = Container::make("navigation");
        foreach ($nav as $navItem):
            /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
            if ($navItem->hasChildren()):
                include "dropdown.phtml";
            else:
                echo sprintf($regularLink, $navItem->getUri(), $navItem->getName());
            endif;
        endforeach;
        ?>
    </ul>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Multi Level <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Level 1</a></li>
                <li class="dropdown-submenu"> <a tabindex="-1" href="#">More options</a>
                    <ul class="dropdown-menu">
                        <li><a tabindex="-1" href="#">Level 2</a>
                        </li>
                        <li class="dropdown-submenu"> <a href="#">More..</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Level 3</a>
                                </li>
                                <li><a href="#">Level 3</a>
                                </li>
                                <li class="dropdown-submenu"> <a href="#">More..</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li class="dropdown-submenu"> <a href="#">More..</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Level 5</a>
                                                </li>
                                                <li><a href="#">Level 5</a>
                                                </li>
                                            </ul>
                                        </li>

                                    </ul>
                                </li>

                            </ul>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                    </ul>
                </li>
                <li><a href="#">Level 1</a></li>
            </ul>
        </li> 
    </ul>

    <?php
    $itemCount = "Leeg";
    $sess = Container::make("session");

    // Set the cwd to the basepath again.
    // Else the autoloader tries to load from the wrong location.
    chdir(BASE_PATH);
    $cart_name = Cart::SESSION_NAME;
    if ($sess->has($cart_name)):
        $count = $sess->$cart_name->itemCount();
        if ($count > 0):
            $itemCount = $count;
        endif;
    endif;
    ?>
    <p class="navbar-text navbar-right">
        <span class="glyphicon glyphicon-shopping-cart"></span> 
        <a href="/cart/show/" class="navbar-link">
            <?php echo $itemCount; ?>
        </a>
    </p>

    <?php 
    $login_name = Loggedin::SESSION_NAME;
    if ($sess->has($login_name)): 
        ?>
        <p class="navbar-text navbar-right">
            <a href="/Account/Logout">Logout</a>
        </p>
        <p class="navbar-text navbar-right">
            Welcome <?php echo sprintf("%s", $sess->$login_name->getName()); ?>
        </p>
    <?php else: ?>
        <p class="navbar-text navbar-right">
            <a href="/Account/Login">Login</a>
        </p>
        <p class="navbar-text navbar-right">
            <a href="/Account/Register">Register</a>
        </p>
    <?php endif;
    ?>
</div>
<!-- /.navbar-collapse -->