<?php

use Aggressiveswallow\Tools\Container;
use Aggressiveswallow\Helpers\Cart;
use Aggressiveswallow\Helpers\LoginHelper as Login;

function generateMenu() {

    $nav = Aggressiveswallow\Tools\Container::make("navigation");
    foreach ($nav as $navItem):
        generateLink($navItem);
    endforeach;
}

function generateLink($navItem) {
    $regularLink = "<li><a href=\"%s\">%s</a></li>";
    $menuLink = "<a href=\"%s\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">%s <b class=\"caret\"></b></a>";
    /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
    if ($navItem->hasChildren()) {
        echo "<li class='dropdown'>";
        echo sprintf($menuLink, $navItem->getUri(), $navItem->getName())."categoriëen";
        echo "<ul class='dropdown-menu'>";
        foreach ($navItem->getChildren() as $childItem):
            generateChild($childItem);
        endforeach;
        echo "</ul>";
    }else {
        echo sprintf($regularLink, $navItem->getUri(), $navItem->getName())."home";
    }
    echo "</li>";
}

function generateChild($navItem) {
    $regularLink = "<li><a href=\"%s\">%s</a></li>";
    /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
    if ($navItem->hasChildren()) {
        echo "<li class='dropdown-submenu'>";
        echo sprintf($regularLink, $navItem->getUri(), $navItem->getName())."huizen";
        echo "<ul class='dropdown-menu'>";
        foreach ($navItem->getChildren() as $childItem):
            generateChild($childItem);
        endforeach;
        echo "</ul>";
    }else {
        echo sprintf($regularLink, $navItem->getUri(), $navItem->getName())."kamer";
    }
    echo "</li>";
}
?>


<div class = "collapse navbar-collapse">
    <ul class = "nav navbar-nav">
        <?php
        generateMenu();
        ?>
    </ul>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Multi Level <b class="caret"></b></a>
            <ul class="dropdown-menu">
                
                <li><a href="#">Level 1</a></li>
                
                <li class="dropdown-submenu"> <a tabindex="-1" href="#">More options</a>
                    <ul class="dropdown-menu">
                        
                        <li><a href="#">Level 2</a></li>
                        
                        <li class="dropdown-submenu"> <a href="#">More..</a>
                            <ul class="dropdown-menu">
                                
                                <li><a href="#">Level 3</a></li>
                                
                                <li><a href="#">Level 3</a></li>
                                
                                <li class="dropdown-submenu"> <a href="#">More..</a>
                                    <ul class="dropdown-menu">
                                        
                                        <li><a href="#">Level 4</a></li>
                                        
                                        <li><a href="#">Level 4</a></li>
                                        
                                        <li class="dropdown-submenu"> <a href="#">More..</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Level 5</a>
                                                </li>
                                                <li><a href="#">Level 5</a>
                                                </li>
                                            </ul>
                                        </li>

                                    </ul>
                                </li>

                            </ul>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                    </ul>
                </li>
                
                <li><a href="#">Level 1</a></li>
            </ul>
        </li>
    </ul>

    <?php
    chdir(BASE_PATH);
    $sess = Container::make("session");
    $cartText = "Leeg";
    $cart_name = Cart::SESSION_NAME;
    if ($sess->has($cart_name)):
        $count = $sess->$cart_name->itemCount();
        if ($count > 0):
            $cartText = sprintf(($count == 1 ? " %s item" : "%s items"), $count);

        endif;
    endif;
    ?>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="/cart/show/"><span class="glyphicon glyphicon-shopping-cart"></span><?php echo $cartText; ?></a></li>
        <li class="dropdown">
            <?php
            $user = Login::getLoggedInUser();
            $text = (Login::isLoggedIn()) ? $user->getName() : "Niet ingelogd";
            ?>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $text; ?> <b class="caret"></b></a>

            <ul class="dropdown-menu">
                <?php if (!Login::isLoggedIn()): ?>
                    <li><a href="/account/login">Inloggen</a></li>
                    <li><a href="/account/register">Registreren</a></li>
                <?php else: ?>
                    <li><a href="/account/logout">Uitloggen</a></li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
</div>
<!-- /.navbar-collapse -->