<?php

use Aggressiveswallow\Tools\Container;
use Aggressiveswallow\Helpers\Cart;
use Aggressiveswallow\Helpers\LoginHelper as Login;
?>
<div class = "collapse navbar-collapse">
    <ul class = "nav navbar-nav">
        <?php
        $regularLink = "<li><a href=\"%s\">%s</a></li>";
        $nav = Container::make("navigation");
        foreach ($nav as $navItem):
            /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
            if ($navItem->hasChildren()):
                include "dropdown.phtml";
            else:
                echo sprintf($regularLink, $navItem->getUri(), $navItem->getName());
            endif;
        endforeach;
        ?>
    </ul>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Multi Level <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Level 1</a></li>
                <li class="dropdown-submenu"> <a tabindex="-1" href="#">More options</a>
                    <ul class="dropdown-menu">
                        <li><a tabindex="-1" href="#">Level 2</a>
                        </li>
                        <li class="dropdown-submenu"> <a href="#">More..</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Level 3</a>
                                </li>
                                <li><a href="#">Level 3</a>
                                </li>
                                <li class="dropdown-submenu"> <a href="#">More..</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li><a href="#">Level 4</a>
                                        </li>
                                        <li class="dropdown-submenu"> <a href="#">More..</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Level 5</a>
                                                </li>
                                                <li><a href="#">Level 5</a>
                                                </li>
                                            </ul>
                                        </li>

                                    </ul>
                                </li>

                            </ul>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                        <li><a href="#">Level 2</a>
                        </li>
                    </ul>
                </li>
                <li><a href="#">Level 1</a></li>
            </ul>
        </li>
    </ul>

    <p class="navbar-text navbar-right">
        <span class="glyphicon glyphicon-user"></span> 
        <?php
        chdir(BASE_PATH);
        if (Login::isLoggedIn()):
            $user = Login::getLoggedInUser();
            printf("Welkom %s <a href=\"/account/logout/\" class=\"navbar-link\">Uitloggen</a>", $user->getName());
        else:
            echo "<a href=\"/account/login/\" class=\"navbar-link\">Inloggen</a> :: ";
            echo "<a href=\"/account/register/\" class=\"navbar-link\">Registreren</a>";
        endif;
        ?>

    </p>
    <p class="navbar-text navbar-right">
        <span class="glyphicon glyphicon-shopping-cart"></span> 
        <?php
        $itemCount = "Leeg";
        $sess = Container::make("session");

        // Set the cwd to the basepath again.
        // Else the autoloader tries to load from the wrong location.
        chdir(BASE_PATH);
        $cart_name = Cart::SESSION_NAME;
        if ($sess->has($cart_name)):
            $count = $sess->$cart_name->itemCount();
            if ($count > 0):
                $text = sprintf(($count == 1 ? " %s item" : "%s items"), $count);
                echo sprintf("<a href=\"/cart/show/\" class=\"navbar-link\">%s</a>", $text);
            else:
                echo "Leeg";
            endif;
        endif;
        ?>

    </p>
</div>
<!-- /.navbar-collapse -->